# MOTOR
MOTOR_STOP = "0"
MOTOR_FORWARD = "1"
MOTOR_BACKWARD = "2"
MOTOR_RIGHT_ON_PLACE = "3"
MOTOR_LEFT_ON_PLACE = "4"
MOTOR_RIGHT_FORWARD = "5"
MOTOR_RIGHT_BACKWARD = "6"
MOTOR_LEFT_FORWARD = "7"
MOTOR_LEFT_BACKWARD = "8"

# MANIPULATOR
MANIPULATOR_DEFAULT_POSITION = "10"
MANIPULATOR_CLOSE_CLAW = "11"
MANIPULATOR_OPEN_CLAW = "12"
MANIPULATOR_SET_THROW_POSITION = "13"
MANIPULATOR_SET_DOWN_POSITION = "14"
# передавать со значением угла
MANIPULATOR_MOVE_MAIN = "15"
MANIPULATOR_MOVE_CUBIT = "16"
MANIPULATOR_MOVE_WRIST = "17"
MANIPULATOR_MOVE_CLAW = "18"
MANIPULATOR_GRAB = "19"

# CAMERA
CAMERA_DEFAULT_POSITION = "30"
# передавать со значением угла
CAMERA_MOVE_CUBIT = "31"
CAMERA_MOVE_ROTATE = "32"


# SETTINGS
# передавать с параметром цвета
SET_COLOR_ROBOT = "42"
GREEN = 4
RED = 1

ROBOT_COLOR = GREEN